name: ShadowJar with Java 19

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Jar
        run: ./gradlew shadowJar

      # Upload this built jar
      - name: Upload final jar
        uses: actions/upload-artifact@v3
        with:
          name: fat-jar
          path: ./build/libs/FutureRestore GUI-1.0-all.jar
